version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ufrocoin_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ufrocoin_network

  backend:
    build: ./backend
    container_name: ufrocoin_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://root:secretpassword@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
    networks:
      - ufrocoin_network

  frontend:
    build: ./frontend
    container_name: ufrocoin_frontend
    ports:
      - "5173:5173" # Puerto por defecto de Vite
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita sobreescribir los módulos de node del contenedor
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - ufrocoin_network

volumes:
  mongo_data:

networks:
  ufrocoin_network:
    driver: bridge
