name: CI Placeholder
on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  setup-check:
    name: Sprint 0 - Validacion de Entorno
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Confirmacion de Pipeline
        run: |
          echo "Pipeline de CI para UFROCoin detectado y operativo."
          echo "Estado: Sprint 0 - Entorno listo para desarrollo."